# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch:
  push:
    branches: [ "CI_dev" ]
  pull_request:
    branches: [ "CI_dev" ]

permissions:
  contents: read

jobs:
  build:
    name: "Build python shared library"
    runs-on: ubuntu-latest #[self-hosted, linux, x64, gpu]
    strategy:
      matrix:
        py_vers: ["3.10"]
    timeout-minutes: 40
    env:
      PY_VERS: ${{ matrix.py_vers }}
    steps:
    - uses: actions/checkout@v3
    - name: Setup conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        python-version: ${{ matrix.py_vers }}
        conda-channels: anaconda, nvidia
    - name: Install CUDA environment in conda
      run: |
        conda --version
        conda install cuda --yes
        nvcc --version 
    # - name: Manually download CUDA toolkit
    #   uses: Jimver/cuda-toolkit@v0.2.11
    #   id: cuda-toolkit
    #   with:
    #     cuda: '12.1.0'
    #     method: 'network'
    #     linux-local-args: '["--toolkit"]'
    # - run: |
    #     echo "Installed cuda version is: ${{steps.cuda-toolkit.outputs.cuda}}"
    #     echo "Cuda install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
    - name: Build python library
      run: |
        python setup.py build_ext --inplace
    #- name: Install dependencies
    #  run: |
    #    python -m pip install --upgrade pip
    #    pip install cualgo pytest
    #    if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    #- name: Lint with flake8
      #run: |
      #  # stop the build if there are Python syntax errors or undefined names
      #  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      #  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
      #  flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test if library built
      run: |
        ls cualgo*.so || ls cualgo*.pyd
    - name: Test with pytest
      run: |
        pytest
